stages:
  download:
    cmd: python sentiment_analysis/data.py
    outs:
      - data/market_comments.csv

  preprocess:
    cmd: python sentiment_analysis/preprocess.py
    deps:
      - data/market_comments.csv
    outs:
      - data/clean_comments.csv

  train:
    cmd: python sentiment_analysis/train.py
    deps:
      - data/clean_comments.csv
      - configs/model.yaml
      - configs/train.yaml
    outs:
      - model.keras
      - tokenizer.pkl
      - label_encoder.pkl
    params:
      - train.batch_size
      - train.epochs

  export:
    cmd: python sentiment_analysis/export.py
    deps:
      - model.keras
    outs:
      - model.onnx
