train:
  batch_size: 128
  epochs: 30
  validation_split: 0.2
  random_seed: 537
mlflow:
  tracking_uri: "http://127.0.0.1:8080"
  experiment_name: "market_sentiment"
model:
  vocab_size: 20000
  embedding_dim: 256
  max_length: 150
  lstm_units: [128, 64, 32]
  dropout: [0.4, 0.4, 0.3]
